version: '2'
services:
  cadvisor:
    image: google/cadvisor
    command:
    - "--housekeeping_interval=30s"
    - "--global_housekeeping_interval=2m"
    - "--disable_metrics=disk,tcp"
    - "--enable_load_reader"
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
    - back
  smart-exporter:
    image: indiehosters/smartmontools
    privileged: true
    networks:
    - back
    entrypoint: "cron"
    command:
    - "--hours=0"
    - "--minutes=23"
    - "--seconds=0"
    - "smartmon-prom"
    volumes:
    - ./textfiles:/textfiles
  smart-short-test:
    image: indiehosters/smartmontools
    privileged: true
    networks:
    - back
    entrypoint: "cron"
    command:
    - "--hours=23"
    - "--minutes=23"
    - "--seconds=0"
    - "short-test"
    volumes:
    - ./textfiles:/textfiles
  smart-long-test:
    image: indiehosters/smartmontools
    privileged: true
    networks:
    - back
    entrypoint: "cron"
    command:
    - "--hours=0"
    - "--minutes=10"
    - "--seconds=0"
    - "--day-of-week=SAT"
    - "long-test"
    volumes:
    - ./textfiles:/textfiles
  node-exporter:
    image: quay.io/prometheus/node-exporter
    volumes:
    - "/proc:/host/proc:ro"
    - "/sys:/host/sys:ro"
    - "/:/rootfs:ro"
    - "./textfiles:/textfiles"
    command: --path.procfs "/host/proc" --path.sysfs /host/sys --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" --collector.textfile.directory "/textfiles"
    networks:
    - back
  web:
    image: nginx
    volumes:
    - ./htpasswd:/etc/nginx/htpasswd
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
    - VIRTUAL_HOST=cadvisor.${HOSTNAME},node-exporter.${HOSTNAME}
    networks:
    - back
    - lb_web
networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.4.0/28
  lb_web:
    external: true
